server:
  port: 8110

logging:
  file:
    name: cx-flow.log
#  level:
#    com:
#      checkmarx:
#        flow:
#          cmd: TRACE
#          service: TRACE
#          controller: TRACE
#    org:
#      apache:
#        http:
#          wire: TRACE
#      springframework:
#        web:
#          client:
#            RestTemplate: TRACE

cx-flow:
  # Agreed upon shared API token
  token: CXIM
  bug-tracker: JIRA
  bug-tracker-impl:
    - CxXml
    - Json
    - GitLab
    - GitHub
    - Csv
    - Azure
  branches:
    - develop
    - master
    - webhooktest
  filter-severity:
    - High
    - Medium
    - Low
  mitre-url: https://cwe.mitre.org/data/definitions/%s.html
  wiki-url: https://checkmarx.atlassian.net/wiki/spaces/AS/pages/79462432/Remediation+Guidance
  codebash-url: https://cxa.codebashing.com/courses/
  auto-profile: false
  #branch-script: D:\\tmp\Branch.groovy
  #zip-exclude: .*.json$, bin\/.*
  list-false-positives: true

checkmarx:
  username: admin
  password: admin
  client-secret: 014DF517-39D1-4453-B7B3-9930C563627C
  base-url: http://localhost
  url: ${checkmarx.base-url}/cxrestapi
  multi-tenant: false
  incremental: false
  scan-preset: All
  configuration: Default Configuration
  team: \CxServer
  scan-timeout: 120
#WSDL Config
  portal-url: ${checkmarx.base-url}/cxwebinterface/Portal/CxWebService.asmx
  #project-script: D:\Utilities\Cx_Flow\CxProject.groovy
  #team-script: D:\\tmp\CxTeam.groovy
  #exclude-files:
  #exclude-folders:

jira:
  url: https://cxflowtest.atlassian.net/
  username: yayolov854@lexu4g.com
  token: u4ny3fzJUaLdg6U7Fr5NA8D3
  project: TES2
  issue-type: Task
  priorities:
    High: High
    Medium: Medium
    Low: Low
    Informational: Lowest
  open-transition: Reopen and start progress
  close-transition: Done
  open-status:
    - To Do
    - In Progress
    #- In Review
  closed-status:
    - Done
  fields:
    - type: result
      name: system-date
      skip-update: true
      offset: 60
      jira-field-name: Due date #Due date (cloud)
      jira-field-type: text
    - type: result
      name: system-date
      skip-update: true
      offset: 30
      jira-field-name: Dude Date #Due date (cloud)
      jira-field-type: text
#    - type: result
#      name: category
#      jira-field-name: Category
#      jira-field-type: label
    - type: result
      name: cwe
      jira-field-name: CWE
      jira-field-type: label
#    - type: result
#      name: loc
#      jira-field-name: Line Numbers
#      jira-field-type: label
#    - type: static
#      name: AppID
#      jira-field-name: AppID
#      jira-field-type: label
#      jira-default-value: "100023"
    - type: static
      name: Source
      jira-field-name: Source
      jira-field-type: single-select
      jira-default-value: "SAST"
#    - type: static 
#      name: Affected_Area
#      jira-field-name: "Affected Area"
#      jira-field-type: cascading-select
#      jira-default-value: Database;Size
  #issue-prefix: "<PREFIX>-"
  #issue-postfix: "-<POSTFIX>"
  #description-prefix: "<PRE>-"
  #description-postfix: "<POST>-"
  close-transition-field: resolution
  close-transition-value: Done
  close-false-positive-transition-value: Won't Do

github:
  webhook-token: 1234
  token: 8ce2812330786b34f979aea507ac37064df3996c
  #config-as-code: cx.config.json
  url: https://github.com
  api-url: https://api.github.com/repos/
  block-merge: true
  error-merge: false
  cx-summary: true

gitlab:
  webhook-token: 1234
  token: XXX
  url: https://gitlab.com
  api-url: https://gitlab.com/api/v4/
  block-merge: true

bitbucket:
  webhook-token: 1234
  token: xxx
  url: https://api.bitbucket.org
  api-path: /2.0

azure:
  webhook-token: cxflow:1234
  token: XXX
  url: https://dev.azure.com/cx-imatlin
  issue-type: issue
  api-version: 5.0
  false-positive-label: false-positive
  block-merge: true
  error-merge: true
  closed-status: Closed
  open-status: Active   

json:
  file-name-format: "[NAMESPACE]-[REPO]-[BRANCH]-[TIME].json"
  data-folder: "D:\\tmp"

cx-xml:
  file-name-format: "[NAMESPACE]-[REPO]-[BRANCH]-[TIME].xml"
  data-folder: "D:\\tmp"

csv:
  file-name-format: "[TEAM]-[PROJECT]-[TIME].csv"
  data-folder: "C:\\tmp"
  include-header: true
  fields:
    - header: Customer field (Application)
      name: application
      default-value: unknown
    - header: Primary URL
      name: static
      #default-value: ${tmp.url}
    - header: severity
      name: severity
    - header: Vulnerability ID
      name: summary
      prefix: "[APP]:"
    - header: file
      name: filename
    - header: Vulnerability ID
      name: summary
    - header: Vulnerability Name
      name: category
    - header: Category ID
      name: cwe
    - header: Description
      name: summary
      prefix: "*"
      postfix: "*"
    - header: Severity
      name: severity
    - header: recommendation
      name: recommendation
    - header: Similarity ID
      name: similarity-id